requests: fix mypy warnings
tuxrun/requests.py:9: error: Module "requests.packages" has no attribute
"urllib3"  [attr-defined]
tuxrun/requests.py:10: error: Skipping analyzing
"requests.packages.urllib3.util.retry": module is installed, but missing
library stubs or py.typed marker  [import]
tuxrun/requests.py:10: note: See
https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>